# Generated by Django 4.2 on 2023-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='date_release',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
    ]
