# Generated by Django 4.2 on 2023-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_manga_date_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='jenre',
            field=models.ManyToManyField(blank=True, null=True, to='Main.genre', verbose_name='Жанры'),
        ),
        migrations.AlterUniqueTogether(
            name='chaptertophoto',
            unique_together={('chapter', 'number')},
        ),
    ]
