# Generated by Django 4.2 on 2023-05-14 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0003_manga_jenre_alter_chaptertophoto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='jenre',
            field=models.ManyToManyField(blank=True, to='Main.genre', verbose_name='Жанры'),
        ),
        migrations.CreateModel(
            name='UserMarkToManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1, verbose_name='Оценка')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.manga', verbose_name='Манга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
